### ISSUE TITLE
find_DAS_files finds no files if experiment_path points directly to the folder with the files

### ISSUE THREAD

**Issue by speleos** [ASN-Norway/simpleDAS#4]
My data is is stored in /mnt/D2A/DAS/OptoDAS_SN44/26OCT-02NOV/20231027/dphi

If I use:

```
datetime_start = "20231027 152045"
duration = datetime.timedelta(seconds=900)
experiment_path="/mnt/D2A/DAS/OptoDAS_SN44/26OCT-02NOV/"
files,channels,samples=simpledas.find_DAS_files(experiment_path,start=datetime_start,duration=duration)

```
I get a list of files.

However, if `experiment_path="/mnt/D2A/DAS/OptoDAS_SN44/26OCT-02NOV/20231027/dphi"
`
I get an empty file list

The problem seems to be coming from the loop that builds ffiddir:

When no dates are found, dates_in_exp assumes the default value "19000101"

435: `dates_in_exp.append("19000101")  # placeholder for no dateinfo`

But, exppath_has_dates is only checked after the start and stop dates are tested.

451:
```if datetime_start.date() <= date1.date() <= datetime_stop.date():
            ffiddir = (
                os.path.join(experiment_path, date_in_exp, datatype)
                if exppath_has_dates
                else experiment_path
            )
```

**Comment by ohwaagaard** [comment]
Your right, setting experiment_path directly to the path with the files does not work. 
I will look into it.

**Comment by ohwaagaard** [comment]
@speleos I have now now pushed an update to the master branch. Can you check if this works for you?
`pip install git+https://github.com/ASN-Norway/simpleDAS.git` 
should give you this version.  
Note that you want clone simpledas code to a location of your choice, change directory to a suitable location, and clone:  
`git clone https://github.com/ASN-Norway/simpleDAS.git`
then go to the created simpledas directory, and append this to your python_path with  
`pip install -e .`
