### ISSUE TITLE
Regions of interest are reported incorrectly depending on how get_data_indexes is defined

### ISSUE THREAD

**Issue by speleos** [ASN-Norway/simpleDAS#5]
https://github.com/ASN-Norway/simpleDAS/blob/fdc4511ece7ce350ca65e28ca91ba2f8f9e8cc07/src/simpledas/simpleDASreader.py#L498C1-L498C1

Regions of interest are wrongly reported when invoking simpledas.get_data_indexes, but correct when the function is defined separately (i.e. copied and pasted from the repository into a script)

Copied and pasted function:
get_data_indexes("/mnt/D2A/DAS/OptoDAS_SN44/26OCT-02NOV/20231027/dphi/152049.hdf5")

-- Header info file: 152049.hdf5 --
	Experiment:            SN044_PHASE_26_10_2023
	File timestamp:        2023-10-27 15:20:49
	Type of data:          Phase rate per distance, unit: rad/(s*m)
	Sampling frequency:    500.00 Hz
	Data shape:            5000 samples x 11380 channels
	Gauge length:          10.2 m
	Sensitivities:         9.36e+06 rad/(strain*m)
	Regions of interest:   **0:56895:5**

when used with import simpledas:
simpledas.get_data_indexes("/mnt/D2A/DAS/OptoDAS_SN44/26OCT-02NOV/20231027/dphi/152049.hdf5")

-- Header info file: 152049.hdf5 --
	Experiment:            SN044_PHASE_26_10_2023
	File timestamp:        2023-10-27 15:20:49
	Type of data:          Phase rate per distance, unit: rad/(s*m)
	Sampling frequency:    500.00 Hz
	Data shape:            5000 samples x 11380 channels
	Gauge length:          10.2 m
	Sensitivities:         9.36e+06 rad/(strain*m)
	Regions of interest:   **0:56895:4**

On this experiment, only each fifth channel is read and thus Regions of interest:   0:56895:5 is the correct answer.

**Comment by ohwaagaard** [comment]
Hi, thanks for your feedback.
This issue I believed is solved in the latest release 8.2.2.
