### ISSUE TITLE
Deprecation warning in pd.timedelta_range

### ISSUE THREAD

**Issue by speleos** [ASN-Norway/simpleDAS#7]
https://github.com/ASN-Norway/simpleDAS/blob/5d1a15484fff1fb757e3640cfd67d3d572b7a34c/src/simpledas/simpleDASreader.py#L922

On a recent installation, I received the following warning:

(...) lib/python3.12/site-packages/simpledas/simpleDASreader.py:921: FutureWarning: 'N' is deprecated and will be removed in a future version, please use 'ns' instead.

**Comment by ohwaagaard** [comment]
Fixed in v8.2.3
